version: '2'
services:
  caddy-proxy:
    build: .
    image: scortum/caddy-proxy
    container_name: caddy-proxy
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./certs:/etc/caddy/certs"
      - "./logs:/var/log/www"
    ports:
      - "80:80"
      - "443:443"
      - "2015:2015"

#  hello-world:
#    image: tutum/hello-world
#    container_name: hello-world
#    environment:
#      - VIRTUAL_HOST=helloworld.local

  whoami:
    image: jwilder/whoami
    container_name: whoami
    environment:
      - VIRTUAL_HOST=whoami.local


